SELECT * FROM Region;
SELECT * FROM SalesOrder;
SELECT * FROM SalesOrder LIMIT 500;
---- COUNT TOTAL NUMBER_OF_ROWS AND COULUMNS IN A TABLE_AND_DATABASE----
------ num_of_colm for the_whole_dabase
SELECT COUNT(*) AS TOTAL_NUM_OF_ROW FROM region;
SELECT COUNT(*) AS NUMBER_OF_COLUMNS FROM INFORMATION_SCHEMA. COLUMNS; 
---- num_of_
SELECT COUNT(*) AS NUMBER_OF_COLUMNS FROM INFORMATION_SCHEMA. COLUMNS
WHERE TABLE_NAME = 'region';
SELECT COUNT(*) AS NUMBER_OF_COLUMNS FROM INFORMATION_SCHEMA. COLUMNS
WHERE TABLE_NAME = 'orderdetail';
SELECT COUNT(*) AS NUMBER_OF_COLUMNS FROM INFORMATION_SCHEMA. COLUMNS
WHERE TABLE_NAME = 'salesorder';
SELECT COUNT(*) AS NUMBER_OF_COLUMNS FROM INFORMATION_SCHEMA. COLUMNS
WHERE TABLE_NAME = 'Supplier';
SELECT COUNT(*) AS NUMBER_OF_COLUMNS FROM INFORMATION_SCHEMA. COLUMNS
WHERE TABLE_NAME = 'Customer';
SELECT COUNT(*) AS NUMBER_OF_COLUMNS FROM INFORMATION_SCHEMA. COLUMNS
WHERE TABLE_NAME = 'product';
SELECT COUNT(*) AS NUMBER_OF_COLUMNS FROM INFORMATION_SCHEMA. COLUMNS
WHERE TABLE_NAME = 'Employee';
SELECT COUNT(*) AS NUMBER_OF_COLUMNS FROM INFORMATION_SCHEMA. COLUMNS
WHERE TABLE_NAME = 'shipper';
SELECT COUNT(*) AS TOTAL_NUM_OF_ROW FROM product;
SELECT COUNT(*) AS TOTAL_NUM_OF_ROW FROM orderdetail;
SELECT COUNT(*) AS TOTAL_NUM_OF_ROW FROM region;
SELECT COUNT(*) AS TOTAL_NUM_OF_ROW FROM employee;
SELECT COUNT(*) AS TOTAL_NUM_OF_ROW FROM supplier;
SELECT COUNT(*) AS TOTAL_NUM_OF_ROW FROM shipper;
SELECT COUNT(*) AS TOTAL_NUM_OF_ROW FROM salesorder;
SELECT COUNT(*) AS TOTAL_NUM_OF_ROW FROM  Customer;

show databases;
SELECT *FROM  Customer;
SELECT *FROM Customer LIMIT 10; 
UPDATE Customer
SET fax = '456-7811'
WHERE custID = 3;

UPDATE customer
SET REGION = 'WEST ASIA'
WHERE CUSTID = 1;

UPDATE customer
SET REGION = 'EUROPE'
WHERE CUSTID = 2;

UPDATE customer
SET REGION = 'ASIA'
WHERE CUSTID = 3;

UPDATE customer
SET REGION = 'AFRICA'
WHERE CUSTID = 4;

UPDATE customer
SET REGION = 'PACIFIC'
WHERE CUSTID = 5;

UPDATE customer
SET REGION = 'EAST EUROPE'
WHERE CUSTID = 6;

UPDATE customer
SET REGION = 'MID EAST'
WHERE CUSTID = 7;
UPDATE customer
SET region = CASE
WHEN CUSTID = 8 THEN "WEST EURO"
WHEN CUSTID = 9 THEN "SOUTH AMERICA"
WHEN CUSTID = 10 THEN "ATLANTIC"
END
WHERE CUSTID in (8,9,10);

UPDATE customer
SET mobile = '08066092829'
WHERE CUSTID = 1;

UPDATE customer
SET mobile = '07066098292'
WHERE CUSTID = 2;
SELECT * FROM customer ;

UPDATE customer
SET mobile = '07066098888'
WHERE CUSTID = 3;

UPDATE customer
SET mobile = '0706666660'
WHERE CUSTID = 4;
UPDATE Customer 
SET mobile = CASE
WHEN CUSTID = 5  THEN '09066258741'
WHEN CUSTID = 6 THEN '07055547896'
WHEN CUSTID = 7 THEN '80666321445'
WHEN CUSTID = 8 THEN '08077458691'
WHEN CUSTID = 9 THEN '09105487962'
WHEN CUSTID = 10 THEN '0817549632'
END 
WHERE CUSTID in (5,6,7,8,9,10);

UPDATE Customer 
SET email = CASE
WHEN CUSTID = 5 THEN 'FAD@GMAIL.COM'
WHEN CUSTID = 6 THEN 'FTY@YAHOO.COM'
WHEN CUSTID = 7 THEN 'NABIL@GMAIL.COM'
WHEN CUSTID = 8 THEN 'AISH@YAHOO.COM'
WHEN CUSTID = 9 THEN 'MUHIB@GMAIL.COM'
WHEN CUSTID = 10 THEN 'YUSYUS@GMAIL.COM'
END 
WHERE CUSTID in (5,6,7,8,9,10);

UPDATE customer
SET email = 'ty@gmail.com'
WHERE CUSTID = 1;

UPDATE customer
SET email = 'fty@yahoo.com'
WHERE CUSTID = 2;

UPDATE customer
SET email = 'nabil@gmail.com'
WHERE CUSTID = 3;
UPDATE customer
SET email = 'aish@yahoo.com'
WHERE CUSTID = 4;

SELECT * FROM customer LIMIT 10;

SELECT * FROM salesorder;
SELECT * FROM orderdetail;
--- HOW TO JOIN TABLES---
SELECT *
FROM salesorder
JOIN orderdetail
		ON salesorder.orderid = orderdetail.orderid;
        

        SELECT * FROM customer;
        
        SELECT *
        FROM customer
        WHERE contactName LIKE "B%";
        
         SELECT *
        FROM customer
        WHERE contactName LIKE "%B";
        
		SELECT *
        FROM customer
        WHERE contactName LIKE "%B%";
        
         SELECT *
        FROM customer
        WHERE country LIKE "U_";
        UPDATE customer
        SET region = "AMERICA"
        WHERE CUSTID = 11;
        